// <auto-generated />
using System;
using GitHubPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubPractice.Migrations
{
    [DbContext(typeof(MembershipContext))]
    [Migration("20251014205636_AddBirthDateToMembership")]
    partial class AddBirthDateToMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitHubPractice.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1988, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JoinDate = new DateTime(2025, 6, 28, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            Name = "Frank Furter"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JoinDate = new DateTime(2025, 1, 28, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cookie Crumb"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JoinDate = new DateTime(2025, 1, 1, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sierra Madre"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JoinDate = new DateTime(2025, 2, 14, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ima Winner"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JoinDate = new DateTime(2025, 3, 7, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            Name = "Truly Sporty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
